---

- name: install packages
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - apt-transport-https
    - software-properties-common

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    id: "0xB1998361219BD9C9"
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present

- name: install zulu repository for OpenJDK
  apt_repository:
    repo: deb http://repos.azulsystems.com/ubuntu stable main
    state: present
    filename: zulu-openjdk

- name: install OpenJDK
  apt:
    name: "zulu-{{ zulu_openjdk_version }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoremove: yes
    update_cache: yes

...
